name: sockets_mqtt_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^8.0.3
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  injectable: ^2.1.1
  auto_route: ^9.3.0+1
  mqtt_client: ^10.11.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner:

flutter:
  uses-material-design: true

